/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MXObservation struct {

	// Description of the MX-Record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the MX-record to be added/updated, as a map in JSON format.
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// FQDN for the MX-record.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A record used to specify mail server.
	MailExchanger *string `json:"mailExchanger,omitempty" tf:"mail_exchanger,omitempty"`

	// Configures the preference (0-65535) for this MX-record.
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// TTL value for the MX-record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type MXParameters struct {

	// Description of the MX-Record.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within
	// +kubebuilder:validation:Optional
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the MX-record to be added/updated, as a map in JSON format.
	// +kubebuilder:validation:Optional
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// FQDN for the MX-record.
	// +kubebuilder:validation:Optional
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// A record used to specify mail server.
	// +kubebuilder:validation:Optional
	MailExchanger *string `json:"mailExchanger,omitempty" tf:"mail_exchanger,omitempty"`

	// Configures the preference (0-65535) for this MX-record.
	// +kubebuilder:validation:Optional
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// TTL value for the MX-record.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// MXSpec defines the desired state of MX
type MXSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MXParameters `json:"forProvider"`
}

// MXStatus defines the observed state of MX.
type MXStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MXObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// MX is the Schema for the MXs API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infoblox-nios}
type MX struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.fqdn)",message="fqdn is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.mailExchanger)",message="mailExchanger is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.preference)",message="preference is a required parameter"
	Spec   MXSpec   `json:"spec"`
	Status MXStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MXList contains a list of MXs
type MXList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MX `json:"items"`
}

// Repository type metadata.
var (
	MX_Kind             = "MX"
	MX_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MX_Kind}.String()
	MX_KindAPIVersion   = MX_Kind + "." + CRDGroupVersion.String()
	MX_GroupVersionKind = CRDGroupVersion.WithKind(MX_Kind)
)

func init() {
	SchemeBuilder.Register(&MX{}, &MXList{})
}
