/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AllocationObservation struct {

	// The address in cidr format.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// A description of IP address allocation.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Dns View under which the zone has been created.
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// flag that defines if the host record is to be used for DNS Purposes.
	EnableDNS *bool `json:"enableDns,omitempty" tf:"enable_dns,omitempty"`

	// The extensible attributes for IP address allocation, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The host name for Host Record in FQDN format.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address of cloud instance.Set a valid IP for static allocation and leave empty if dynamically allocated.
	IPAddr *string `json:"ipAddr,omitempty" tf:"ip_addr,omitempty"`

	// Network view name of NIOS server.
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`

	// TTL attribute value for the record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type AllocationParameters struct {

	// The address in cidr format.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// A description of IP address allocation.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Dns View under which the zone has been created.
	// +kubebuilder:validation:Optional
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// flag that defines if the host record is to be used for DNS Purposes.
	// +kubebuilder:validation:Optional
	EnableDNS *bool `json:"enableDns,omitempty" tf:"enable_dns,omitempty"`

	// The extensible attributes for IP address allocation, as a map in JSON format
	// +kubebuilder:validation:Optional
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The host name for Host Record in FQDN format.
	// +kubebuilder:validation:Optional
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// IP address of cloud instance.Set a valid IP for static allocation and leave empty if dynamically allocated.
	// +kubebuilder:validation:Optional
	IPAddr *string `json:"ipAddr,omitempty" tf:"ip_addr,omitempty"`

	// Network view name of NIOS server.
	// +kubebuilder:validation:Optional
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`

	// TTL attribute value for the record.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// AllocationSpec defines the desired state of Allocation
type AllocationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AllocationParameters `json:"forProvider"`
}

// AllocationStatus defines the observed state of Allocation.
type AllocationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AllocationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Allocation is the Schema for the Allocations API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infoblox-nios}
type Allocation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.fqdn)",message="fqdn is a required parameter"
	Spec   AllocationSpec   `json:"spec"`
	Status AllocationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AllocationList contains a list of Allocations
type AllocationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Allocation `json:"items"`
}

// Repository type metadata.
var (
	Allocation_Kind             = "Allocation"
	Allocation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Allocation_Kind}.String()
	Allocation_KindAPIVersion   = Allocation_Kind + "." + CRDGroupVersion.String()
	Allocation_GroupVersionKind = CRDGroupVersion.WithKind(Allocation_Kind)
)

func init() {
	SchemeBuilder.Register(&Allocation{}, &AllocationList{})
}
